version: "1.0"
info:
  model: int-scaffold
packages:
- name: LDSGH1908Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
- name: MultiplyPublicService
  version: "6.0"
  gitServerName: srcCtrl_shared_bitbucket_Arti
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: artikhare
  gitBranch: master
services:
- serviceName: project.ldsgh1908.integrations:bitbucketfs
  packages:
  - name: LDSGH1908Project
    version: "1.0"
  - name: MultiplyPublicService
    version: "6.0"
- serviceName: MultiplyPublicService:multiply_svc
  packages:
  - name: MultiplyPublicService
    version: "6.0"
- serviceName: pub.math:multiplyInts
  packages:
  - name: WmPublic
    version: 12.1.0.0.1101
